#!/usr/bin/env node
/**
 * count-lint.mjs — Generated by quality-ratchet
 * Reads ESLint JSON output from stdin and prints error/warning counts.
 * Usage: npx eslint . --ext ts,tsx --format json | node scripts/count-lint.mjs
 */

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => (input += chunk));
process.stdin.on('end', () => {
  try {
    const data = JSON.parse(input);
    let errors = 0;
    let warnings = 0;
    for (const file of data) {
      errors   += file.errorCount   ?? 0;
      warnings += file.warningCount ?? 0;
    }
    console.log(`ESLint: ${errors} errors, ${warnings} warnings`);
  } catch {
    console.error('Failed to parse ESLint JSON output');
    process.exit(1);
  }
});
